"""
Configuration file for the Sphinx documentation builder.

This file only contains a selection of the most common options. For a full
list see the documentation:
https://www.sphinx-doc.org/en/master/usage/configuration.html

Instructions for compiling documentation:
-----------------------------------------

- Dynamic content is generated from json products so need to create/update
  product specification files

  * Update vocal if required by deleting and recreating conda environment
  * In repo root create a release

  ```shell
    ~/spif$ conda activate vocal
    (vocal) ~/spif$ vocal release standard/v0 -v 0.1 -o .
  ```

- Run sphinx to create documentation in spif/docs/build. (I have sphinx in
  my spif environment.)

  ```shell
    ~/spif$ conda activate spif
    (spif) ~/spif$ cd docs
    (spif) ~/spif$ make html
```

- To push html to website, Dave must create build on his machine.

"""

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))
import os.path
import sys
import datetime
import sphinx_rtd_theme
import sphinx_design

import pdb

# Directory of spif standard
std_dir = os.path.abspath(
                os.path.join(os.path.dirname(__file__), '..', '..', 'standard')
                )
dyn_dir = os.path.abspath(
                os.path.join(os.path.dirname(__file__), 'dynamic_content')
                )
if std_dir not in sys.path:
    sys.path.insert(0, std_dir)
if dyn_dir not in sys.path:
    sys.path.insert(0, dyn_dir)

from versions import __standard_version__, __product_version__

# -- Project information -----------------------------------------------------
project_short_name = "SPIF"
project_long_name = "Single Particle Image Format"
project = f"{project_short_name} – {project_long_name}"
date = datetime.datetime.now().date().isoformat()
copyright = f'{date}, G J Nott, D Sproson'
author = 'SPIF team'

# The full version, including alpha/beta/rc tags
release = f"{__product_version__:0.3}"


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx_design',      # Furo theme
              'sphinx_rtd_theme',   # Read the docs theme
#              'sphinx.ext.autodoc', # Auto doc code documentation
              'sphinx.ext.napoleon', # Google style docstrings
            ]

napoleon_include_init_with_doc = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
#language = en

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ['Thumbs.db', '.DS_Store', 'build*', 'templates*']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, '()' will be appended to :func: etc. cross-reference text.
add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
add_module_names = True

# A string of reStructuredText that will be included at the beginning
# of every source file that is read.
# s5defs.txt builtin with html colors etc
rst_prolog = """
 .. include:: <s5defs.txt>

 """

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'furo'#sphinx_design'


# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
html_css_files = ['css/custom_text.css']#, 'css/faam.css']
#html_logo = "_static/faam-small.png"
html_title = f"{project_short_name}: v{release}"
html_theme_options = {'top_of_page_button': None,
                     }


# -- Options for LaTeX output -------------------------------------------------
latex_elements = {
    'papersize': 'a4paper',
    'extraclassoptions': 'openany,oneside',
    'preamble': r'''
        \definecolor{FAAMDarkBlue}{HTML}{252243}
        \definecolor{FAAMLightBlue}{HTML}{0ABBEF}
        \usepackage{eso-pic}
        \usepackage{pict2e}
        \newcommand\BackgroundPic{
        \put(300,-260){
            \color{FAAMLightBlue}\circle*{900}
        }
        \put(300,-260){
            \color{FAAMDarkBlue}\circle*{760}
        }
    }''',
    # Pretty hacky this - escaping from the sphinx macros,
    # but it sorta kinda works well enough.
    'maketitle': '''
        \\AddToShipoutPicture*{{\\BackgroundPic}}
        \\begin{{titlepage}}
            \\color{{FAAMDarkBlue}}
            \\begin{{flushright}}
                \\sphinxlogo
                {{\\sffamily
                    {{\\Huge \\textbf{{ {project} }}}}
                    \\par\\vspace{{1cm}}
                    {{\\itshape\\LARGE\\textbf{{ Release {release} }}}}
                    \\par\\vspace{{3cm}}
                    {{\\LARGE \\textbf{{{author}}}}}
                    \\par\\vspace{{3cm}}
                    {{\\Large \\textbf{{{date}}}}}
                 }}
             \\end{{flushright}}
        \\end{{titlepage}}
        '''.format(
            project=project,
            release=release,
            author=author,
            date=datetime.date.today().strftime('%B %-d, %Y')
        )
}
latex_logo = '_static/faam.png'